// Generated by ReScript, PLEASE EDIT WITH CARE


function make(config) {
  return {
    connection: "Disconnected",
    auth: "Anonymous",
    room: "NotInRoom",
    capabilities: undefined,
    config: config,
    socketRef: undefined,
    channelRef: undefined
  };
}

function profileDefaults(p) {
  if (typeof p === "object") {
    return p._0;
  }
  switch (p) {
    case "Gaming" :
      return {
        inputMode: {
          TAG: "PushToTalk",
          _0: "KeyV"
        },
        noiseSuppression: true,
        echoCancellation: false,
        spatialAudio: true,
        e2ee: false,
        targetLatencyMs: 20,
        bitrateKbps: 32
      };
    case "Workspace" :
      return {
        inputMode: "VoiceActivity",
        noiseSuppression: true,
        echoCancellation: true,
        spatialAudio: false,
        e2ee: true,
        targetLatencyMs: 40,
        bitrateKbps: 48
      };
    case "Broadcast" :
      return {
        inputMode: "VoiceActivity",
        noiseSuppression: true,
        echoCancellation: true,
        spatialAudio: false,
        e2ee: false,
        targetLatencyMs: 100,
        bitrateKbps: 96
      };
  }
}

function connect(client) {
  client.connection = "Connecting";
  client.config.onConnectionChange("Connecting");
  client.config.extensions.forEach(ext => {
    let cb = ext.onConnect;
    if (cb !== undefined) {
      return cb(client);
    }
  });
}

function disconnect(client) {
  client.config.extensions.forEach(ext => {
    let cb = ext.onDisconnect;
    if (cb !== undefined) {
      return cb(client);
    }
  });
  client.room = "NotInRoom";
  client.auth = "Anonymous";
  client.connection = "Disconnected";
  client.config.onConnectionChange("Disconnected");
}

function secureIdSuffix() {
  const b = new Uint8Array(4);
  crypto.getRandomValues(b);
  return Array.from(b, x => x.toString(16).padStart(2, "0")).join("");
}

function guestLogin(client, displayName) {
  let guestId = "guest_" + secureIdSuffix();
  client.auth = {
    TAG: "Guest",
    id: guestId,
    displayName: displayName
  };
  client.config.onAuthChange(client.auth);
}

function setAuth(client, auth) {
  client.auth = auth;
  client.config.onAuthChange(auth);
}

function joinRoom(client, roomId, serverId) {
  client.room = {
    TAG: "Joining",
    _0: roomId
  };
  client.config.onRoomChange(client.room);
  client.config.extensions.forEach(ext => {
    let cb = ext.onRoomJoin;
    if (cb !== undefined) {
      return cb(client, roomId);
    }
  });
}

function leaveRoom(client) {
  client.config.extensions.forEach(ext => {
    let cb = ext.onRoomLeave;
    if (cb !== undefined) {
      return cb(client);
    }
  });
  client.room = "NotInRoom";
  client.config.onRoomChange("NotInRoom");
}

function registerExtension(client, ext) {
  client.config.extensions.concat([ext]);
}

function token(client) {
  let match = client.auth;
  if (typeof match !== "object" || match.TAG === "Guest") {
    return;
  } else {
    return match.accessToken;
  }
}

function isInRoom(client) {
  let match = client.room;
  if (typeof match !== "object") {
    return false;
  } else {
    return match.TAG !== "Joining";
  }
}

function isAuthenticated(client) {
  let match = client.auth;
  return typeof match === "object";
}

export {
  make,
  profileDefaults,
  connect,
  disconnect,
  guestLogin,
  setAuth,
  joinRoom,
  leaveRoom,
  registerExtension,
  token,
  isInRoom,
  isAuthenticated,
}
/* No side effect */
